In [4]:
# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load the Pima Indian Diabetes dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/pima-indians-diabetes/pima-indians-diabetes.data"
column_names = ["Pregnancies", "Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI", "DiabetesPedigreeFunction", "Age", "Outcome"]
diabetes_data = pd.read_csv('diabetes.csv')

# Split the data into features (X) and target variable (y)
X = diabetes_data.drop("Outcome", axis=1)
y = diabetes_data["Outcome"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Gradient Boosting Classifier
gb_classifier = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Train the classifier
gb_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = gb_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Print the results
print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)


Accuracy: 0.75
Confusion Matrix:
[[78 21]
 [18 37]]
Classification Report:
              precision    recall  f1-score   support

           0       0.81      0.79      0.80        99
           1       0.64      0.67      0.65        55

    accuracy                           0.75       154
   macro avg       0.73      0.73      0.73       154
weighted avg       0.75      0.75      0.75       154



In [5]:
diabetes_data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [7]:
class_counts = diabetes_data["Outcome"].value_counts()

# Display the counts
print("Class counts:")
print(class_counts)

Class counts:
Outcome
0    500
1    268
Name: count, dtype: int64


In [8]:
df = diabetes_data

In [10]:
from sklearn.utils import resample
column_name = "Outcome"
majority_class = df[df[column_name] == 0]
minority_class = df[df[column_name] == 1]

# Upsample the minority class
minority_upsampled = resample(minority_class, replace=True, n_samples=len(majority_class), random_state=42)

# Combine the majority class with the upsampled minority class
upsampled_df = pd.concat([majority_class, minority_upsampled])

# Display the upsampled DataFrame
print("Upsampled DataFrame:")
print(upsampled_df)

Upsampled DataFrame:
     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
1              1       85             66             29        0  26.6   
3              1       89             66             23       94  28.1   
5              5      116             74              0        0  25.6   
7             10      115              0              0        0  35.3   
10             4      110             92              0        0  37.6   
..           ...      ...            ...            ...      ...   ...   
612            7      168             88             42      321  38.2   
586            8      143             66              0        0  34.9   
730            3      130             78             23       79  28.4   
664            6      115             60             39        0  33.7   
425            4      184             78             39      277  37.0   

     DiabetesPedigreeFunction  Age  Outcome  
1                       0.351   31        0 

In [11]:
upsampled_df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
1              1       85             66             29        0  26.6   
3              1       89             66             23       94  28.1   
5              5      116             74              0        0  25.6   
7             10      115              0              0        0  35.3   
10             4      110             92              0        0  37.6   
..           ...      ...            ...            ...      ...   ...   
612            7      168             88             42      321  38.2   
586            8      143             66              0        0  34.9   
730            3      130             78             23       79  28.4   
664            6      115             60             39        0  33.7   
425            4      184             78             39      277  37.0   

     DiabetesPedigreeFunction  Age  Outcome  
1                       0.351   31        0  
3                       0.167   21        0  
5                       0.201   30        0  
7                       0.134   29        0  
10                      0.191   30        0  
..                        ...  ...      ...  
612                     0.787   40        1  
586                     0.129   41        1  
730                     0.323   34        1  
664                     0.245   40        1  
425                     0.264   31        1  

[1000 rows x 9 columns]

In [13]:
class_counts = upsampled_df["Outcome"].value_counts()

# Display the counts
print("Class counts:")
print(class_counts)

Class counts:
Outcome
0    500
1    500
Name: count, dtype: int64


In [14]:
diabetes_data = upsampled_df

In [20]:
# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


# Split the data into features (X) and target variable (y)
X = diabetes_data.drop("Outcome", axis=1)
y = diabetes_data["Outcome"]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Gradient Boosting Classifier
gb_classifier = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Train the classifier
gb_classifier.fit(X_train, y_train)

# Make predictions on the test set
y_pred = gb_classifier.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

# Print the results
print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)


Accuracy: 0.84
Confusion Matrix:
[[76 20]
 [12 92]]
Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.79      0.83        96
           1       0.82      0.88      0.85       104

    accuracy                           0.84       200
   macro avg       0.84      0.84      0.84       200
weighted avg       0.84      0.84      0.84       200



In [19]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01, 0.1, 1],
    'max_depth': [3, 4, 5],
    'min_samples_leaf': [1, 2, 3],
    'subsample': [0.6, 0.8, 1.0]
}

# Initialize the GridSearchCV
grid_search = GridSearchCV(gb_classifier, param_grid, cv=5, scoring='accuracy', n_jobs=-1)

# Fit the GridSearchCV
grid_search.fit(X_train, y_train)

# Get the best parameters
best_params = grid_search.best_params_

# Print the best parameters
print(f"Best parameters: {best_params}")

# Train the classifier with the best parameters
gb_classifier_best = GradientBoostingClassifier(**best_params)
gb_classifier_best.fit(X_train, y_train)

# Make predictions on the test set
y_pred_best = gb_classifier_best.predict(X_test)

# Evaluate the model
accuracy_best = accuracy_score(y_test, y_pred_best)
conf_matrix_best = confusion_matrix(y_test, y_pred_best)
classification_rep_best = classification_report(y_test, y_pred_best)

# Print the results
print(f"Accuracy (with best parameters): {accuracy_best:.2f}")
print("Confusion Matrix (with best parameters):")
print(conf_matrix_best)
print("Classification Report (with best parameters):")
print(classification_rep_best)


Best parameters: {'learning_rate': 1, 'max_depth': 5, 'min_samples_leaf': 1, 'n_estimators': 100, 'subsample': 1.0}
Accuracy (with best parameters): 0.84
Confusion Matrix (with best parameters):
[[80 16]
 [16 88]]
Classification Report (with best parameters):
              precision    recall  f1-score   support

           0       0.83      0.83      0.83        96
           1       0.85      0.85      0.85       104

    accuracy                           0.84       200
   macro avg       0.84      0.84      0.84       200
weighted avg       0.84      0.84      0.84       200



In [21]:
print(best_params)

{'learning_rate': 1, 'max_depth': 5, 'min_samples_leaf': 1, 'n_estimators': 100, 'subsample': 1.0}


In [18]:
diabetes_data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
1              1       85             66             29        0  26.6   
3              1       89             66             23       94  28.1   
5              5      116             74              0        0  25.6   
7             10      115              0              0        0  35.3   
10             4      110             92              0        0  37.6   
..           ...      ...            ...            ...      ...   ...   
612            7      168             88             42      321  38.2   
586            8      143             66              0        0  34.9   
730            3      130             78             23       79  28.4   
664            6      115             60             39        0  33.7   
425            4      184             78             39      277  37.0   

     DiabetesPedigreeFunction  Age  Outcome  
1                       0.351   31        0  
3                       0.167   21        0  
5                       0.201   30        0  
7                       0.134   29        0  
10                      0.191   30        0  
..                        ...  ...      ...  
612                     0.787   40        1  
586                     0.129   41        1  
730                     0.323   34        1  
664                     0.245   40        1  
425                     0.264   31        1  

[1000 rows x 9 columns]